### ISSUE TITLE
Man,e,where  is the implementation.....

### ISSUE THREAD

**Issue by heartInsert** [ildoonet/pytorch-randaugment#1]

**Comment by ildoonet** [comment]
Working on it. It will release within one or two weeks.

**Comment by haqishen** [comment]
Hahaha there's a hurry-up issue!
2 weeks past I'm looking forward for your implementation as well!

**Comment by jizongFox** [comment]
2 weeks have past and I'm looking forward for your implementation as well!

**Comment by yuxiwang93** [comment]
2 weeks have past and I'm looking forward to your implementation as well!

**Comment by jizongFox** [comment]
Hi, I have added an implementation in the PR.

**Comment by lingyongguo** [comment]
2 weeks have past and I'm looking forward to your implementation as well!

**Comment by ivylinden** [comment]
2 weeks have past and I'm looking forward to your implementation as well!

**Comment by ildoonet** [comment]
Guys, I;ve just uploaded implementations.

Sorry for the delay. I'm still conducting experiments to reproduce the paper's result. For Wide-ResNet-28-10 on CIFAR-100 dataset, I got the similar result. 

I need to try to reproduce the paper's result futhermore for other architectures and ImageNet.

Thanks.

**Comment by ildoonet** [comment]
I've reproduced results for Wide-ResNet-28x10 for both of cifar-10 and cifar-100. 

I believe that there aren't any significant problem in implementation codes.

I started experiments for other architectures on CIFAR-10, CIFAR-100 and ImageNet.

I will update readme as soon as I got reproduced valid result. 

Thanks! I'm closing this.

**Comment by alup** [comment]
Is there any chance to provide an alternative implementation based on OpenCV?
