### ISSUE TITLE
"theconf" error

### ISSUE THREAD

**Issue by nd26** [ildoonet/pytorch-randaugment#10]
Hi there, thank you for your effort in trying to replicate the experimental results of RandAugment. I've cloned the repository, and I am trying to rerun RandAugment on Cifar10, but the following error comes up:

`python RandAugment/train.py -c confs/wresnet28x10_cifar10_b256.yaml --save cifar10_wres28x10.pth
File "RandAugment/train.py", line 13, in <module>
    from theconf import Config as C, ConfigArgumentParser
ImportError: cannot import name 'Config'
`

I've installed theconf from https://github.com/ildoonet/theconf, but it seems that it is an outdated version of what you are using, as there is no Config class.

**Comment by ildoonet** [comment]
@nd26 Please use this : https://github.com/wbaek/thecon

Sorry for the inconveniences. Install requirements.txt will install all required dependencies.

**Comment by ildoonet** [comment]
I guess you can resolve now, I'm closing this but if you need any further assistance, please let me know.
