### ISSUE TITLE
Posterize function error

### ISSUE THREAD

**Issue by learningman7777** [ildoonet/pytorch-randaugment#13]
hello. thank for your repo!

I found an minor error in Posterize function when I used RandAugment class.
although a comment was written # [4, 8], 
actually, [0, 4] have being passed.

when v=0, a image have not level, so a image is all black.
I think that v must be more than 2.

Anyway, thank you for making RandAugment on pytorch!
It is helpful!

**Comment by ildoonet** [comment]
@learningman7777 Thanks for the report. 

I just cross-checked with the original repository.

As I committed new code now, it is now producing same transformed images as author's code. Zero level should be replaced to 1.

But, as you said, transformation is less when level for posterize is bigger.  I think randaugment's all augmentations should be harder when we increase level. 

@BarretZoph , Can you check on this? Below images are generated using your code and levels are 0, 1, 2, 3, and 4, respectively. I expected orders of below images are reversed.

![doggy_tf0](https://user-images.githubusercontent.com/1115758/73340982-0ea36f00-42bf-11ea-85b7-c717e9ad8693.jpg)
level=0
![doggy_tf1](https://user-images.githubusercontent.com/1115758/73340985-106d3280-42bf-11ea-81b0-fc39b88e0a83.jpg)
level=1
![doggy_tf2](https://user-images.githubusercontent.com/1115758/73340991-1236f600-42bf-11ea-98b0-ff5d7df11aca.jpg)
level=2
![doggy_tf3](https://user-images.githubusercontent.com/1115758/73340995-1400b980-42bf-11ea-8671-a11294b9ff40.jpg)
level=3
![doggy_tf4](https://user-images.githubusercontent.com/1115758/73340998-15ca7d00-42bf-11ea-94ae-85d99f93de07.jpg)
level=4


Reference
- https://github.com/tensorflow/tpu/blob/a0d7a57a782d76d3c3c1343c06dbb148cc2e1be1/models/official/efficientnet/autoaugment.py#L513
- https://github.com/tensorflow/tpu/blob/a0d7a57a782d76d3c3c1343c06dbb148cc2e1be1/models/official/efficientnet/autoaugment.py#L225

**Comment by ildoonet** [comment]
@learningman7777 I found the author's response on this. If you have any further questions and think this resolve the problem, please close this issue.

https://github.com/tensorflow/tpu/issues/637#issuecomment-571286096

**Comment by learningman7777** [comment]
thanks!
