### ISSUE TITLE
about the peformance of randAugment and baseline

### ISSUE THREAD

**Issue by JiyueWang** [ildoonet/pytorch-randaugment#7]
I have run the wresnet28x10_cifar10_b256 with the yaml file you provide
the top1_test is 0.9706, and when I set the aug to 'default' and retrain the model, I got 0.9694.
Did I do something wrong to make the randAugment perform worse than you claimed and baseline perform better?

**Comment by ildoonet** [comment]
What is your environment?
- Pytorch Version
- CUDA Version
- Python Version
...

**Comment by ildoonet** [comment]
Close due to inactivity.
